name: Build and test.

on:
  pull_request: # Run tests for any PRs.

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Get golint
      run: go get -u golang.org/x/lint/golint
    - name: Run Vet & Lint
      run: |
        go vet ./...
        echo $(go list -f {{.Target}} golang.org/x/lint/golint)
        $(go list -f {{.Target}} golang.org/x/lint/golint) -set_exit_status=1 ./...