name: Build-and-test

on:
  push:
    branches:
    - main # run tests and code-coverage/vet/lint when code is pushed to main
  pull_request: # Run tests for any PRs.

jobs:
  test:
    strategy:
      matrix:
        go-version: [1.13.x, 1.15.x]
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Test
      run: go test ./...
    - name: Get golint
      run: go get -u golang.org/x/lint/golint
    - name: Run Vet & Lint
      run: |
        go vet ./...
        echo $(go list -f {{.Target}} golang.org/x/lint/golint)
        $(go list -f {{.Target}} golang.org/x/lint/golint) -set_exit_status=1 ./...

  code-coverage:
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build
      run: go build .
    - name: Test With Coverage
      run: go test -gcflags=-l -v  -coverprofile=coverage.txt -covermode=atomic ./...
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
